# Workflow for checking all new commits to main

name: CI

on:
  push:
    branches: # Trigger on commits to main
      - main
    tags:
      - v* # Also version tags to avoid skipping releases

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out main Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Run tests
        run: mvn clean verify -B

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out main Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Run static checks
        run: mvn compile -B -P lint,strict