# Workflow for checking all new commits to main

name: CI Checks

on:
  push:
    branches: # Trigger on commits to main
      - main

concurrency: ci-checks
jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out main Git repository
        uses: actions/checkout@v2
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Run style checks
        run: mvn validate -B -P style,strict