# Workflow for testing that the code of incoming pull requests builds and passes tests

name: Run Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency: pr-test-${{ github.ref }}
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v2
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn clean verify -B