# Workflow for testing that the code of incoming pull requests builds with strict checking

name: Linter Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency: pr-lint-${{ github.ref }}
jobs:
  tests:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v2
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Build classes
        run: mvn clean install -B -Dmaven.test.skip=true # Just need the classes for checker use, no test necessary
      - name: Run linter/checker
        run: mvn compile -B -P lint,strict